### ISSUE TITLE
win10 mingw

### ISSUE THREAD

**Issue by strayer-ckey** [ejoy/vaststars#13]
![1718624806018](https://github.com/ejoy/vaststars/assets/75315194/9dcd12f5-8c6e-4af1-a280-1ded40b99007)

**Comment by cloudwu** [comment]
不要用截图发文本。

**Comment by cloudwu** [comment]
https://github.com/ejoy/ant/commits/18460ccacfda54dc747c2e43356f31895b4427e3/  这应该修好了这个问题。
